version: '3'

services:
  nginx:
    image: nginx:1.25.0-alpine
    container_name: nginx
    restart: always
    ports:
      - '12300:12300'
      - '443:443'
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./logs/nginx/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
    environment:
      - TZ=Asia/Seoul
  blue:
    image: ${DOCKER_APP_NAME}
    container_name: ${DOCKER_APP_NAME}-blue
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Seoul
  green:
    image: ${DOCKER_APP_NAME}
    container_name: ${DOCKER_APP_NAME}-green
    restart: always
    expose:
      - 3000
    environment:
      - TZ=Asia/Seoul